# LiteLLM 代理配置文件
# 注意：此文件中的配置可以被环境变量覆盖
# 请参考 .env.example 文件了解可用的环境变量

model_list:
  - model_name: "my-custom-model"  # 按照官方文档格式
    litellm_params:
      model: "my-custom-llm/my-model"  # 按照官方文档格式：provider/model

# 根据官方文档添加litellm_settings来注册自定义处理器
litellm_settings:
  custom_provider_map:
    - {"provider": "my-custom-llm", "custom_handler": "custom_handler.my_custom_llm"}
  
  # 非入侵式日志配置
  set_verbose: true          # 启用详细日志
  json_logs: true           # JSON格式日志
  success_callback: []      # 成功回调
  failure_callback: []      # 失败回调

server_settings:
  # 以下设置可通过环境变量 LITELLM_PROXY_PORT 和 LITELLM_PROXY_HOST 覆盖
  port: 8080
  host: 0.0.0.0