version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

loggers:
  litellm:
    level: INFO
    handlers: [console]
    propagate: false
  custom_handler:
    level: DEBUG
    handlers: [console]
    propagate: false
    
root:
  level: INFO
  handlers: [console]